language: objective-c
branches:
  only:
    - master
osx_image: xcode11.3
cache:
  bundler: true
  directories:
    - $HOME/.cocoapods/
before_install:
  - bundle install --deployment && pod repo update
install: true
script:
  - bundle exec rspec && cd spec && ./integration_test.sh
