source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!
use_frameworks!

def shared_pods
    pod 'MRProgress', '~> 0.8'
    pod 'SDCAlertView', '= 2.5.3'
    pod 'SwiftLint', '~> 0.27'
    pod 'MidtransKit', '1.15.4'
    pod 'MoPub-Applovin-Adapters', '10.3.2.0'
end

target 'Test' do
    inherit! :search_paths
    platform :ios, '11.0'

    shared_pods
end

target 'Test2' do
    inherit! :search_paths
    platform :ios, '11.0'

    shared_pods
end

target 'TestWatch Extension' do
    platform :watchos, '2.0'

    pod 'KeychainAccess', '~> 3.1'
end

post_install do |installer|
    installer.pods_project.targets
        .select {|target| target.name == "KeychainAccess"}
        .map(&:build_configurations)
        .flatten
        .each {|configuration| configuration.build_settings['SWIFT_VERSION'] = '4.0'}
end
