name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2

    - name: Install bundle
      run: bundle install --deployment
    
    - name: Update pods repo
      run: pod repo update
    
    - name: Run Ruby tests
      run: bundle exec rspec
    
    - name: Run integration tests
      run: cd spec && ./integration_test.sh
