name: CI

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: macos-11
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"

    steps:
      - uses: actions/checkout@v2

      - name: Select Xcode 13
        run: sudo xcode-select -s /Applications/Xcode_13.0.app

      - name: Install bundle
        run: gem install bundler:1.17.3 && bundle install --deployment

      - name: Update pods repo
        run: pod repo update

      - name: Run Ruby tests
        run: bundle exec rspec

      - name: Run integration tests
        run: cd spec && ./integration_test.sh
