name: CI

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: macos-12
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1

      - name: Install bundle
        run: gem update --system && bundle install

      - name: Update pods repo
        run: pod repo update

      - name: Run Ruby tests
        run: bundle exec rspec

      - name: Run integration tests
        run: cd spec && ./integration_test.sh
